### ISSUE TITLE
compatibility with ghc-8

### ISSUE THREAD

**Issue by lspitzner** [haskell-distributed/rank1dynamic#15]
~~~~
src/Data/Rank1Typeable.hs:113:32: error:
    Module ‘Data.Typeable.Internal’ does not export ‘tcList’

src/Data/Rank1Typeable.hs:113:40: error:
    Module ‘Data.Typeable.Internal’ does not export ‘tcFun’
~~~~

Btw, the ["official" bug tracker](https://cloud-haskell.atlassian.net/projects/RANKNDYN/issues/RANKNDYN-1?filter=allopenissues) did not work in my firefox, effectively threw away my filled out issue form because i was not logged in (which is a wild guess; it did not allow me to submit the issue with some "no reporter" error, but there is no "reporter" field on the form) and then refused to let me register with one of my usual mail addresses.

Thanks for providing this package.

**Comment by facundominguez** [comment]
Hello @lspitzner, I think this has been fixed in bd647b47. Let me know if not.

The bugtracker link needs to point here. It is worth keeping this open until changing it an making a new release.

**Comment by lspitzner** [comment]
indeed, master works with ghc-8; thanks.

**Comment by facundominguez** [comment]
Made a new release. https://hackage.haskell.org/package/rank1dynamic-0.3.3.0
