### ISSUE TITLE
build failed on Nix server

### ISSUE THREAD

**Issue by pshemass** [haskell-distributed/rank1dynamic#24]
i was trying to use distributed-process-0.7.4 with nix but it seems that build is failing https://hydra.nixos.org/build/86431664 because of rank1dynamic build is failing. 

please take a look on the logs https://hydra.nixos.org/build/86437016/log

let me know if there is an easy way to fix or workaround this.

**Comment by facundominguez** [comment]
It shouldn't be difficult to fix the tests for 8.6. I think I'd try relaxing the error check so it accepts both `->` and `(->)` disregarding the compiler version.

**Comment by facundominguez** [comment]
I think this is fixed in #23. Please, reopen if this is not the case.
