### ISSUE TITLE
Test failure with ghc-9.2.4 (FUN instead of `->`)

### ISSUE THREAD

**Issue by TristanCacqueray** [haskell-distributed/rank1dynamic#26]
It seems like the tests are failing with ghc-9.2.4 with this error:

```
  CANNOT use a term of type 'forall a. a -> a' as 'forall a. a': [Failed]
expected: Left "Cannot unify Skolem and ->"
 but got: Left "Cannot unify Skolem and FUN"
```

Should we add a new funKindStr value in https://github.com/haskell-distributed/rank1dynamic/blob/master/tests/test.hs#L10-L15 ?

**Comment by facundominguez** [comment]
Hello! Thanks for reporting it.

> Should we add a new funKindStr value in https://github.com/haskell-distributed/rank1dynamic/blob/master/tests/test.hs#L10-L15 ?

Would make sense to me.
